name: Build libraries

on:
  - workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: "/opt/termux/android-sdk"
      NDK: "/opt/termux/android-ndk"

    strategy:
      matrix:
        target_arch: [aarch64, arm, i686, x86_64]
      fail-fast: false

    steps:

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get packages from termux-packages
        uses: actions/checkout@v3
        with:
          repository: termux/termux-packages
          path: termux-packages

      - name: Setup environment
        run: |
          # Use custom packaging properties for JekyllEx
          rm termux-packages/scripts/properties.sh termux-packages/scripts/build-bootstraps.sh
          mv termux-packages/* .
          rm -rf termux-packages
          mv properties.sh build-bootstraps.sh scripts/

      - name: Build ruby and needed dependencies
        run: ./scripts/run-docker.sh ./build-package.sh -a ${{ matrix.target_arch }} glib libxml2 make pkg-config 

      - name: Checksums for built *.deb files
        if: always()
        run: find output -type f -name "*.deb" -exec sha256sum "{}" \; | sort -k2

      - name: Make debs archive
        run: |
          mv output tools
          tar cf tools-${{ matrix.target_arch }}.tar tools/*.deb

      - name: Store debs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: tools-${{ matrix.target_arch }}
          path: "*.tar"

  upload:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Get all artifacts from build action
        uses: actions/download-artifact@v2

      - name: Prepare bootstraps to upload
        if: always()
        run: |
          mkdir -p deps/deps
          for f in tools-*; do cd "$f" && mv "$f".tar ../deps/deps/"${f//tools-/}".tar && cd ..; done

      - name: Upload bootstraps
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          folder: deps
          branch: gh-pages
          clean: false
