name: Build ruby

on:
  - workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: "/opt/termux/android-sdk"
      NDK: "/opt/termux/android-ndk"

    strategy:
      matrix:
        target_arch: [aarch64, arm, i686, x86_64]
      fail-fast: false

    steps:

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get packages from termux-packages
        uses: actions/checkout@v3
        with:
          repository: termux/termux-packages
          path: termux-packages

      - name: Setup environment
        run: |
          # Use custom packaging properties for JekyllEx
          rm termux-packages/scripts/properties.sh termux-packages/scripts/build-bootstraps.sh
          mv termux-packages/* .
          rm -rf termux-packages
          mv properties.sh build-bootstraps.sh scripts/

      - name: Build ruby and needed dependencies
        run: ./scripts/run-docker.sh ./build-package.sh -a ${{ matrix.target_arch }} ruby glib libxml2 make pkg-config libllvm

      - name: Checksums for built *.deb files
        if: always()
        run: find output -type f -name "*.deb" -exec sha256sum "{}" \; | sort -k2

      - name: Make debs archive
        run: |
          mkdir -p ruby/ruby/${{ matrix.target_arch }}
          mv output debs
          tar cf debs-${{ matrix.target_arch }}.tar debs/*.deb
          mv debs/*.deb ruby/ruby/${{ matrix.target_arch }}

      - name: Upload debs
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          folder: ruby
          branch: gh-pages
          clean: false

      - name: Store artifacts
      if: always()
        uses: actions/upload-artifact@v3
        with:
          name: debs-${{ matrix.target_arch }}
          path: "*.tar"
